### ISSUE TITLE
Diagram not rendered with Material for MkDocs theme configured with instant navigation

### ISSUE THREAD

**Issue by lzrf0cuz** [tuunit/mkdocs-drawio#11]
The diagram doesn't get rendered when used with [Material for MkDoc](https://squidfunk.github.io/mkdocs-material) configured with [instant navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading).

Material configuration snippet to replicate the issue.

```yaml
theme:
  name: material
  features:
    - navigation.instant
```

If it is not fixable here, I can link it to the [Material for MkDoc repo](https://github.com/squidfunk/mkdocs-material).
