### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by joapuiib** [tuunit/mkdocs-drawio#30]
I'm using this plugin in Material for MkDocs.

I was wondering if it is possible to render the diagram with a specific theme: light/dark and change it dynamically when the user change between them.

Light mode:

![Image](https://github.com/user-attachments/assets/0a416a00-4762-4d66-a56e-78c053101684)

Actual dark mode:

![Image](https://github.com/user-attachments/assets/7608b37d-d2c6-4cd1-96db-a2eb76909b83)

Expected dark mode:

![Image](https://github.com/user-attachments/assets/d74cacf0-4147-472e-af1f-cd71ad77c0ee)

**Comment by mdlister** [comment]
+1 Dark mode would be amazing

**Comment by tuunit** [comment]
Already implemented in https://github.com/tuunit/mkdocs-drawio/pull/21. I just have to split it into a separate PR

**Comment by tuunit** [comment]
Here we go: https://github.com/tuunit/mkdocs-drawio/pull/32

**Comment by tuunit** [comment]
Released in:
[- Dark Mode 🕶️](https://github.com/tuunit/mkdocs-drawio/releases/tag/v1.11.1)

Check it out on:
https://tuunit.github.io/mkdocs-drawio/tests/simple-diagram/

**Comment by tuunit** [comment]
How to configure:
https://tuunit.github.io/mkdocs-drawio/configuration/

```yaml
plugins:
  - drawio:
      # Control if darkmode is supported
      # When activated the color scheme for your diagrams is automatically toggled
      # based on the selected theme. Supports classic mkdocs and mkdocs-material.
      darkmode: true
```
