### ISSUE TITLE
v1.11.1 - No such file or directory: '/usr/local/lib/python3.13/site-packages/mkdocs_drawio/css/drawio-darkmode.css

### ISSUE THREAD

**Issue by ChrisTav424** [tuunit/mkdocs-drawio#34]
Thank you for implementing Dark mode! [issue30](https://github.com/tuunit/mkdocs-drawio/issues/30)

However if I enable it I get the following error when I add 

```
plugins:
  - drawio:
      darkmode: true
```

```
File "/usr/local/lib/python3.13/site-packages/mkdocs/plugins.py", line 602, in on_post_build
    return self.run_event('post_build', config=config)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/mkdocs/plugins.py", line 568, in run_event
    result = method(**kwargs)
  File "/usr/local/lib/python3.13/site-packages/mkdocs_drawio/plugin.py", line 161, in on_post_build
    copy_file(self.base / path, site / path)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/mkdocs/utils/__init__.py", line 123, in copy_file
    shutil.copyfile(source_path, output_path)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ~~~~^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.13/site-packages/mkdocs_drawio/css/drawio-darkmode.css'
ERROR: Job failed: exit code 1
```

I don't get this issue if I switch back to dark mode false on v1.11.1

```
plugins:
  - drawio:
      darkmode: false
```

**Comment by tuunit** [comment]
Hi @ChrisTav424,

can you share your build command and mkdocs.yaml?

Are you using a special flag like --no-directory-urls or similar?

**Comment by ChrisTav424** [comment]
Yes of course, we do have quite a bit in our mkdocs.yaml :

```
site_name: <redacted>
site_description: <redacted>
repo_name: <redacted>
repo_url: <redacted>
edit_uri: -/edit/master/docs
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: octicons/moon-16
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: octicons/sun-16
        name: Switch to light mode
  font:
    text: "NTA"
    code: "JetBrains Mono"
  logo: assets/hmlr-logo-white.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.code.annotation

    # - search.highlight # not as useful as you'd think
  # - navigation.indexes
  icon:
    annotation: material/help-circle-outline
    repo: fontawesome/brands/gitlab
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - toc:
      permalink: '#'
  - admonition
  - abbr
  - attr_list
  - markdown_include.include:
      base_path: docs
      inheritHeadingDepth: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascript/tablesort.js

plugins:
  - search # required iff plugins: uncommented
  - awesome-pages
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: datetime
  - glightbox
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - javascript/tablesort.js
      css_files:
        - stylesheets/extra.css
  - tags:
      tags_file: <redacted>/tags.md
  - drawio:
      darkmode: false



```
